import { useState, useEffect } from 'react'
import { useCurrentAccount, useSignAndExecuteTransaction, useSuiClient } from '@mysten/dapp-kit'
import { Transaction } from '@mysten/sui/transactions'
import { useNavigate } from 'react-router-dom'
import { fetchVaultsByOwner, mistToSui, PACKAGE_ID } from '../lib/sui.js'
import { Card, Btn, Spinner, PageWrap, SectionLabel, StatNum, Tag } from '../components/ui.jsx'

const DNS_RECORDS = (domain) => [
  {
    type: 'MX',
    label: 'MX — Inbound mail routing',
    description: 'Tells senders which servers receive email for your domain. Cloudflare Email Routing requires all three MX records with the priorities below.',
    records: [
      { name: domain, type: 'MX', priority: '13', value: 'route1.mx.cloudflare.net' },
      { name: domain, type: 'MX', priority: '30', value: 'route2.mx.cloudflare.net' },
      { name: domain, type: 'MX', priority: '20', value: 'route3.mx.cloudflare.net' },
    ],
  },
  {
    type: 'SPF',
    label: 'SPF — Authorised senders',
    description: 'A TXT record that lists which servers are allowed to send email on behalf of your domain. If you already have an SPF record, merge the include rather than adding a second one.',
    records: [
      { name: domain, type: 'TXT', priority: null, value: 'v=spf1 include:_spf.mx.cloudflare.net ~all' },
    ],
  },
  {
    type: 'DKIM',
    label: 'DKIM — Cryptographic signature',
    description: "Cloudflare auto-generates a DKIM key pair when you enable Email Routing. The public key is added automatically — no manual entry needed. Verify the record is present in Dash → Email → Settings → DNS records.",
    records: [
      { name: `cf2024-1._domainkey.${domain}`, type: 'TXT', priority: null, value: '(auto-generated by Cloudflare — check Email → Settings → DNS records)' },
    ],
  },
  {
    type: 'DMARC',
    label: 'DMARC — Policy enforcement',
    description: "Ties SPF and DKIM together and tells receiving servers what to do with unauthenticated mail. Start with p=none to monitor, then tighten to quarantine or reject once you've confirmed legitimate mail passes.",
    records: [
      { name: `_dmarc.${domain}`, type: 'TXT', priority: null, value: `v=DMARC1; p=none; rua=mailto:dmarc@${domain}` },
    ],
  },
]

function DnsRecord({ rec }) {
  return (
    <div style={{
      display: 'grid',
      gridTemplateColumns: rec.priority ? '60px 60px 1fr' : '60px 1fr',
      gap: '8px',
      alignItems: 'start',
      padding: '8px 12px',
      background: 'var(--bg1)',
      borderRadius: 'var(--r)',
      border: '1px solid var(--border)',
      marginBottom: '6px',
    }}>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--accent)', fontWeight: 700, paddingTop: '2px' }}>{rec.type}</span>
      {rec.priority && (
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--text3)', paddingTop: '2px' }}>pri: {rec.priority}</span>
      )}
      <div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--text3)', marginBottom: '2px' }}>{rec.name}</div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text2)', wordBreak: 'break-all', lineHeight: '1.5' }}>{rec.value}</div>
      </div>
    </div>
  )
}

function DnsAccordion({ gatewayEmail }) {
  const [open, setOpen] = useState(false)
  const [openSection, setOpenSection] = useState(null)
  const domain = gatewayEmail?.split('@')[1] || 'yourdomain.com'
  const sections = DNS_RECORDS(domain)

  return (
    <div style={{ marginTop: '12px', border: '1px solid var(--border)', borderRadius: 'var(--r)', overflow: 'hidden' }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '12px 16px', background: 'var(--bg2)', border: 'none', cursor: 'pointer',
          fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text2)',
          letterSpacing: '0.06em', textTransform: 'uppercase',
        }}
      >
        <span>🌐 DNS configuration guide</span>
        <span style={{ color: 'var(--text3)', fontSize: '14px', transition: 'transform 0.2s', display: 'inline-block', transform: open ? 'rotate(180deg)' : 'rotate(0deg)' }}>▾</span>
      </button>

      {open && (
        <div style={{ padding: '16px', background: 'var(--bg1)' }}>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: '12px', color: 'var(--text2)', lineHeight: '1.7', marginBottom: '16px' }}>
            After deploying your Cloudflare Worker, configure the following DNS records on{' '}
            <strong style={{ color: 'var(--text)' }}>{domain}</strong> so the email gateway can receive and authenticate mail correctly.
            Go to <strong style={{ color: 'var(--text)' }}>Cloudflare Dashboard → your domain → DNS → Records</strong> and add each record below.
          </p>

          {sections.map(section => (
            <div key={section.type} style={{ marginBottom: '8px', border: '1px solid var(--border)', borderRadius: 'var(--r)', overflow: 'hidden' }}>
              <button
                onClick={() => setOpenSection(s => s === section.type ? null : section.type)}
                style={{
                  width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                  padding: '10px 14px', background: 'var(--bg2)', border: 'none', cursor: 'pointer',
                  fontFamily: 'var(--font-mono)', fontSize: '11px',
                }}
              >
                <span style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <span style={{
                    background: 'var(--accent)', color: 'var(--bg1)', borderRadius: '4px',
                    padding: '1px 6px', fontSize: '10px', fontWeight: 700, letterSpacing: '0.05em',
                  }}>{section.type}</span>
                  <span style={{ color: 'var(--text2)' }}>{section.label}</span>
                </span>
                <span style={{ color: 'var(--text3)', fontSize: '13px', display: 'inline-block', transition: 'transform 0.2s', transform: openSection === section.type ? 'rotate(180deg)' : 'rotate(0deg)' }}>▾</span>
              </button>

              {openSection === section.type && (
                <div style={{ padding: '12px 14px', borderTop: '1px solid var(--border)' }}>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: '12px', color: 'var(--text3)', lineHeight: '1.6', marginBottom: '12px' }}>
                    {section.description}
                  </p>
                  {section.records.map((rec, i) => <DnsRecord key={i} rec={rec} />)}
                </div>
              )}
            </div>
          ))}

          <div style={{
            marginTop: '14px', padding: '10px 14px',
            background: 'var(--bg2)', borderRadius: 'var(--r)',
            fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text3)', lineHeight: '1.7',
          }}>
            💡 DNS changes can take up to 48 hours to propagate, though usually under 5 minutes on Cloudflare.
            Verify your setup at{' '}
            <a href="https://mxtoolbox.com" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>MXToolbox</a>
            {' '}or{' '}
            <a href="https://toolbox.googleapps.com/apps/checkmx/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>Google Check MX</a>.
          </div>
        </div>
      )}
    </div>
  )
}

const SECRETS = (vaultId, gatewayEmail) => [
  {
    key: 'VAULT_ID',
    value: vaultId,
    description: 'The on-chain object ID of your AttentionVault. The Worker uses this to verify that an incoming email\'s payment_id matches an active slot before letting it through.',
    required: true,
  },
  {
    key: 'SELLER_GATEWAY_EMAIL',
    value: gatewayEmail,
    description: 'The gateway email address assigned to your vault. Inbound emails addressed to this address are intercepted and validated by the Worker.',
    required: true,
  },
  {
    key: 'SUI_RPC_URL',
    value: 'https://fullnode.testnet.sui.io:443',
    description: 'The Sui fullnode RPC endpoint the Worker calls to verify on-chain slot state. Defaults to testnet — swap for mainnet when you go live.',
    required: false,
  },
  {
    key: 'FORWARD_TO_EMAIL',
    value: '(your real inbox)',
    description: 'The destination address the Worker forwards validated emails to. Set this to your actual email address — never expose it publicly.',
    required: true,
  },
]

function SecretRow({ secret }) {
  const [copied, setCopied] = useState(false)

  function copy() {
    navigator.clipboard.writeText(secret.value)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div style={{
      padding: '10px 12px',
      background: 'var(--bg1)',
      borderRadius: 'var(--r)',
      border: `1px solid ${secret.required ? 'var(--border)' : 'var(--border)'}`,
      marginBottom: '8px',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px', gap: '8px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <code style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--accent)', fontWeight: 700 }}>{secret.key}</code>
          {secret.required
            ? <span style={{ fontFamily: 'var(--font-mono)', fontSize: '9px', color: 'var(--amber)', background: 'color-mix(in srgb, var(--amber) 12%, transparent)', borderRadius: '3px', padding: '1px 5px', letterSpacing: '0.05em' }}>REQUIRED</span>
            : <span style={{ fontFamily: 'var(--font-mono)', fontSize: '9px', color: 'var(--text3)', background: 'var(--bg2)', borderRadius: '3px', padding: '1px 5px', letterSpacing: '0.05em' }}>OPTIONAL</span>
          }
        </div>
        <button
          onClick={copy}
          style={{
            fontFamily: 'var(--font-mono)', fontSize: '10px',
            color: copied ? 'var(--teal)' : 'var(--text3)',
            background: 'none', border: 'none', cursor: 'pointer', padding: '2px 6px',
            borderRadius: '4px', transition: 'color 0.2s',
          }}
        >
          {copied ? '✓ copied' : 'copy value'}
        </button>
      </div>
      <code style={{
        display: 'block', fontFamily: 'var(--font-mono)', fontSize: '11px',
        color: 'var(--text2)', wordBreak: 'break-all', marginBottom: '6px',
        padding: '6px 8px', background: 'var(--bg2)', borderRadius: '4px',
      }}>{secret.value}</code>
      <p style={{ fontFamily: 'var(--font-body)', fontSize: '11px', color: 'var(--text3)', lineHeight: '1.6', margin: 0 }}>
        {secret.description}
      </p>
    </div>
  )
}

function SecretsAccordion({ vaultId, gatewayEmail }) {
  const [open, setOpen] = useState(false)
  const secrets = SECRETS(vaultId, gatewayEmail)

  return (
    <div style={{ marginTop: '8px', border: '1px solid var(--border)', borderRadius: 'var(--r)', overflow: 'hidden' }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '12px 16px', background: 'var(--bg2)', border: 'none', cursor: 'pointer',
          fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text2)',
          letterSpacing: '0.06em', textTransform: 'uppercase',
        }}
      >
        <span>🔑 Worker secrets configuration</span>
        <span style={{ color: 'var(--text3)', fontSize: '14px', display: 'inline-block', transition: 'transform 0.2s', transform: open ? 'rotate(180deg)' : 'rotate(0deg)' }}>▾</span>
      </button>

      {open && (
        <div style={{ padding: '16px', background: 'var(--bg1)' }}>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: '12px', color: 'var(--text2)', lineHeight: '1.7', marginBottom: '16px' }}>
            After deploying, set these secrets on your Worker via the Cloudflare dashboard or with Wrangler CLI.
            Secrets are encrypted at rest and never exposed in Worker code.
          </p>

          <div style={{
            display: 'flex', gap: '8px', alignItems: 'flex-start',
            padding: '10px 14px', background: 'var(--bg2)', borderRadius: 'var(--r)',
            marginBottom: '16px', border: '1px solid var(--border)',
          }}>
            <span style={{ fontSize: '14px', flexShrink: 0, marginTop: '1px' }}>⚡</span>
            <div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text2)', marginBottom: '4px', fontWeight: 700 }}>Via Wrangler CLI</div>
              <code style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--accent)', display: 'block', lineHeight: '1.8' }}>
                npx wrangler secret put VAULT_ID<br />
                npx wrangler secret put SELLER_GATEWAY_EMAIL<br />
                npx wrangler secret put FORWARD_TO_EMAIL
              </code>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--text3)', marginTop: '6px' }}>
                Each command prompts you to paste the value — it is never stored in your shell history.
              </div>
            </div>
          </div>

          <div style={{
            display: 'flex', gap: '8px', alignItems: 'flex-start',
            padding: '10px 14px', background: 'var(--bg2)', borderRadius: 'var(--r)',
            marginBottom: '16px', border: '1px solid var(--border)',
          }}>
            <span style={{ fontSize: '14px', flexShrink: 0, marginTop: '1px' }}>🖥️</span>
            <div style={{ fontFamily: 'var(--font-body)', fontSize: '11px', color: 'var(--text3)', lineHeight: '1.7' }}>
              <strong style={{ color: 'var(--text2)' }}>Via dashboard:</strong>{' '}
              Cloudflare Dashboard → Workers & Pages → your Worker → Settings → Variables & Secrets → Add secret.
            </div>
          </div>

          {secrets.map(s => <SecretRow key={s.key} secret={s} />)}

          <div style={{
            marginTop: '6px', padding: '10px 14px',
            background: 'var(--bg2)', borderRadius: 'var(--r)',
            fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text3)', lineHeight: '1.7',
          }}>
            ⚠️ Never commit secrets to your repository. Add <code style={{ color: 'var(--accent)' }}>.dev.vars</code> to <code style={{ color: 'var(--accent)' }}>.gitignore</code> if you use it for local development.
          </div>
        </div>
      )}
    </div>
  )
}

function SlotRow({ slot, index }) {
  const empty = slot.bidder === '0x0000000000000000000000000000000000000000000000000000000000000000'
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 14px',
      background: 'var(--bg2)', borderRadius: 'var(--r)',
      borderLeft: `3px solid ${empty ? 'var(--border)' : 'var(--amber)'}`,
    }}>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text3)', width: '20px' }}>#{index + 1}</span>
      <span style={{ flex: 1, fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text2)' }}>
        {empty ? 'open' : `${slot.bidder.slice(0, 10)}… · hash: ${slot.senderEmailHash?.slice(0, 10) ?? '—'}…`}
      </span>
      <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '13px', color: empty ? 'var(--text3)' : 'var(--amber)' }}>
        {empty ? '—' : `${mistToSui(slot.amount)} SUI`}
      </span>
      {!empty && slot.paymentId && (
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--text3)' }}>
          pid: {slot.paymentId.slice(0, 8)}…
        </span>
      )}
    </div>
  )
}

function CloseThreadModal({ vault, capId, onClose, onDone, signAndExecute }) {
  const [paymentIdInput, setPaymentIdInput] = useState('')
  const [busy, setBusy] = useState(false)
  const [err, setErr]   = useState('')

  async function submit() {
    if (!paymentIdInput.trim()) return
    setBusy(true)
    setErr('')
    try {
      const tx = new Transaction()
      const pidBytes = Array.from(Buffer.from(paymentIdInput.trim(), 'hex'))
      tx.moveCall({
        target: `${PACKAGE_ID}::attention_market::close_conversation`,
        arguments: [
          tx.object(vault.id),
          tx.object(capId),
          tx.pure.vector('u8', pidBytes),
        ],
      })
      await signAndExecute({ transaction: tx })
      onDone()
    } catch (e) {
      setErr(e.message || 'Transaction failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div style={{
      position: 'fixed', inset: 0, background: '#000000cc',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      zIndex: 200, padding: '24px',
    }} onClick={onClose}>
      <div onClick={e => e.stopPropagation()} style={{
        background: 'var(--bg1)', border: '1px solid var(--border)',
        borderRadius: '12px', padding: '28px', width: '100%', maxWidth: '440px',
      }}>
        <div style={{ fontFamily: 'var(--font-display)', fontSize: '18px', fontWeight: 700, marginBottom: '8px' }}>
          Close conversation
        </div>
        <p style={{ fontFamily: 'var(--font-body)', fontSize: '13px', color: 'var(--text2)', lineHeight: '1.7', marginBottom: '20px' }}>
          This permanently invalidates the winner's attention token. The gateway will reject
          all future emails from this thread in both directions. Cannot be undone.
        </p>
        <div style={{ marginBottom: '16px' }}>
          <label style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text3)', letterSpacing: '0.08em', textTransform: 'uppercase', display: 'block', marginBottom: '6px' }}>
            Payment ID (hex)
          </label>
          <input
            value={paymentIdInput}
            onChange={e => setPaymentIdInput(e.target.value)}
            placeholder="64-char hex payment_id from slot"
            style={{
              width: '100%', background: 'var(--bg2)', border: '1px solid var(--border2)',
              borderRadius: 'var(--r)', padding: '10px 14px', color: 'var(--text)',
              fontFamily: 'var(--font-mono)', fontSize: '12px', outline: 'none', boxSizing: 'border-box',
            }}
          />
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text3)', marginTop: '6px' }}>
            Copy the payment_id from the slot row above
          </div>
        </div>
        {err && <div style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--red)', marginBottom: '12px' }}>{err}</div>}
        <div style={{ display: 'flex', gap: '10px' }}>
          <Btn variant="ghost" onClick={onClose} style={{ flex: 1 }}>Cancel</Btn>
          <Btn
            variant="danger"
            onClick={submit}
            disabled={busy || !paymentIdInput.trim()}
            style={{ flex: 1 }}
          >
            {busy ? 'Closing…' : 'Close thread'}
          </Btn>
        </div>
      </div>
    </div>
  )
}

export default function Dashboard() {
  const account = useCurrentAccount()
  const { mutateAsync: signAndExecute } = useSignAndExecuteTransaction()
  const suiClient = useSuiClient()
  const nav = useNavigate()

  const [vaults,  setVaults]  = useState([])
  const [caps,    setCaps]    = useState({}) // vaultId → capObjectId
  const [loading, setLoading] = useState(true)
  const [busy,    setBusy]    = useState({})
  const [modal,   setModal]   = useState(null) // vaultId to show close modal for

  async function fetchVaultCaps(ownerAddress) {
    const res = await suiClient.getOwnedObjects({
      owner: ownerAddress,
      filter: { StructType: `${PACKAGE_ID}::attention_market::VaultCap` },
      options: { showContent: true },
    })
    const caps = {}
    for (const obj of res.data) {
      const vaultId = obj.data?.content?.fields?.vault_id
      if (vaultId) caps[vaultId] = obj.data.objectId
    }
    return caps
  }

  useEffect(() => {
    if (account) load()
    else setLoading(false)
  }, [account?.address])

  async function load() {
    setLoading(true)
    try {
      const [vs, cs] = await Promise.all([
        fetchVaultsByOwner(account.address),
        fetchVaultCaps(account.address),
      ])
      setVaults(vs)
      setCaps(cs)
    } catch (e) { console.error(e) }
    finally { setLoading(false) }
  }

  async function vaultAction(vaultId, fn) {
    const capId = caps[vaultId]
    if (!capId) return alert('VaultCap not found — are you the owner?')
    setBusy(b => ({ ...b, [vaultId]: fn }))
    try {
      const tx = new Transaction()
      tx.moveCall({
        target: `${PACKAGE_ID}::attention_market::${fn}`,
        arguments: [tx.object(vaultId), tx.object(capId)],
      })
      await signAndExecute({ transaction: tx })
      setTimeout(load, 2000)
    } catch (e) { console.error(e) }
    finally { setBusy(b => ({ ...b, [vaultId]: null })) }
  }

  if (!account) return (
    <PageWrap>
      <div style={{ textAlign: 'center', padding: '80px 0' }}>
        <div style={{ fontFamily: 'var(--font-display)', fontSize: '20px', marginBottom: '8px' }}>Connect your wallet</div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text3)' }}>Required to view your seller dashboard</div>
      </div>
    </PageWrap>
  )

  if (loading) return (
    <PageWrap><div style={{ display: 'flex', justifyContent: 'center', padding: '80px' }}><Spinner /></div></PageWrap>
  )

  return (
    <PageWrap>
      {modal && (
        <CloseThreadModal
          vault={vaults.find(v => v.id === modal)}
          capId={caps[modal]}
          onClose={() => setModal(null)}
          onDone={() => { setModal(null); setTimeout(load, 2000) }}
          signAndExecute={signAndExecute}
        />
      )}

      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '32px' }}>
        <div>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: '24px', fontWeight: 800, marginBottom: '4px' }}>Seller dashboard</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text3)' }}>{account.address.slice(0, 16)}…</div>
        </div>
        <Btn onClick={() => nav('/register')} variant="outline">+ New vault</Btn>
      </div>

      {vaults.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '60px 0' }}>
          <div style={{ fontSize: '40px', marginBottom: '16px' }}>📭</div>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: '18px', fontWeight: 600, marginBottom: '8px' }}>No vaults yet</div>
          <Btn onClick={() => nav('/register')} style={{ marginTop: '8px' }}>List my attention →</Btn>
        </div>
      ) : vaults.map(vault => (
        <Card key={vault.id} style={{ padding: '28px', marginBottom: '20px' }}>

          {/* Header */}
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '20px', flexWrap: 'wrap', gap: '12px' }}>
            <div>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: '20px', fontWeight: 700, marginBottom: '4px' }}>{vault.name}</div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--accent)', marginBottom: '4px' }}>{vault.gatewayEmail}</div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--text3)', wordBreak: 'break-all' }}>{vault.id}</div>
            </div>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              <Tag color={vault.slotsAvailable > 0 ? 'var(--teal)' : 'var(--amber)'}>
                {vault.slotsAvailable > 0 ? `${vault.slotsAvailable} open` : 'Full'}
              </Tag>
              <Tag>Epoch {vault.epoch}</Tag>
              {!caps[vault.id] && <Tag color="var(--red)">No cap found</Tag>}
            </div>
          </div>

          {/* Stats */}
          <div style={{ display: 'flex', gap: '16px', marginBottom: '20px', flexWrap: 'wrap' }}>
            <StatNum value={`${mistToSui(vault.balance)} SUI`} label="Pending" accent="var(--accent)" />
            <StatNum value={`${mistToSui(vault.totalEarned)} SUI`} label="Total earned" />
            <StatNum value={vault.totalBids} label="Total bids" />
            <StatNum value={`${mistToSui(vault.floorBid)} SUI`} label="Floor bid" />
          </div>

          {/* Slots */}
          <div style={{ marginBottom: '20px' }}>
            <SectionLabel>Current slots</SectionLabel>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              {vault.slots.map((slot, i) => <SlotRow key={i} slot={slot} index={i} />)}
            </div>
          </div>

          {/* Actions */}
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', paddingTop: '16px', borderTop: '1px solid var(--border)' }}>
            <Btn
              onClick={() => vaultAction(vault.id, 'withdraw')}
              disabled={vault.balance === 0 || !!busy[vault.id]}
            >
              {busy[vault.id] === 'withdraw' ? 'Withdrawing…' : `Withdraw ${mistToSui(vault.balance)} SUI`}
            </Btn>
            <Btn
              variant="ghost"
              onClick={() => vaultAction(vault.id, 'settle_epoch')}
              disabled={!!busy[vault.id]}
            >
              {busy[vault.id] === 'settle_epoch' ? 'Settling…' : 'Settle epoch'}
            </Btn>
            <Btn
              variant="ghost"
              onClick={() => nav(`/profile/${vault.id}`)}
            >
              View profile
            </Btn>
            <Btn
              variant="danger"
              onClick={() => setModal(vault.id)}
              disabled={!!busy[vault.id]}
            >
              Close a thread
            </Btn>
          </div>

          {/* Email Gateway Banner */}
          <div style={{
            marginTop: '20px',
            padding: '18px 20px',
            background: 'linear-gradient(135deg, color-mix(in srgb, var(--accent) 8%, var(--bg2)), color-mix(in srgb, var(--accent) 4%, var(--bg1)))',
            border: '1px solid color-mix(in srgb, var(--accent) 25%, var(--border))',
            borderRadius: 'var(--r)',
          }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '16px', flexWrap: 'wrap' }}>
              <div style={{ flex: 1, minWidth: '200px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                  <span style={{ fontSize: '16px' }}>⚡</span>
                  <span style={{ fontFamily: 'var(--font-display)', fontSize: '14px', fontWeight: 700, color: 'var(--text)' }}>
                    Deploy your email gateway
                  </span>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: '12px', color: 'var(--text2)', lineHeight: '1.7', margin: '0 0 12px 0' }}>
                  Your vault is live on-chain, but incoming emails won't be gated yet. Deploy a Cloudflare Worker that sits in front of your inbox — it verifies every sender holds a valid auction slot before the email reaches you.
                  Without it, anyone can still email <strong style={{ color: 'var(--text)', fontFamily: 'var(--font-mono)', fontSize: '11px' }}>{vault.gatewayEmail}</strong> for free.
                </p>
                <a
                  href="https://deploy.workers.cloudflare.com/?url=<YOUR_REPO_URL>"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <img
                    src="https://deploy.workers.cloudflare.com/button"
                    alt="Deploy to Cloudflare"
                    style={{ height: '32px' }}
                  />
                </a>
              </div>
              <div style={{
                fontFamily: 'var(--font-mono)', fontSize: '10px', color: 'var(--text3)',
                lineHeight: '2', flexShrink: 0,
                padding: '10px 14px', background: 'var(--bg1)',
                borderRadius: 'var(--r)', border: '1px solid var(--border)',
              }}>
                <div style={{ color: 'var(--text2)', fontWeight: 700, marginBottom: '4px', fontSize: '10px', letterSpacing: '0.06em', textTransform: 'uppercase' }}>Worker env vars</div>
                <div><span style={{ color: 'var(--text3)' }}>VAULT_ID</span> <span style={{ color: 'var(--accent)' }}>=</span> <span style={{ color: 'var(--text2)' }}>{vault.id.slice(0, 18)}…</span></div>
                <div><span style={{ color: 'var(--text3)' }}>SELLER_GATEWAY_EMAIL</span> <span style={{ color: 'var(--accent)' }}>=</span> <span style={{ color: 'var(--text2)' }}>{vault.gatewayEmail}</span></div>
              </div>
            </div>
          </div>

          {/* DNS Configuration Accordion */}
          <DnsAccordion gatewayEmail={vault.gatewayEmail} />

          {/* Secrets Configuration Accordion */}
          <SecretsAccordion vaultId={vault.id} gatewayEmail={vault.gatewayEmail} />
        </Card>
      ))}
    </PageWrap>
  )
}